@baseurl = http://localhost:8080

GET {{ baseurl }}/api/v1/flights
Accept: application/json



###
POST  {{ baseurl }}/api/v1/flights
Accept: application/json
Content-Type: application/json

{
  "code": "0502",
  "departDate": "15-05-2022",
  "departTime": "16:30:00",
  "arrivalTime": "19:45:00"
}

###

POST  {{ baseurl }}/api/v1/flights
Accept: application/json
Content-Type: application/json

{
  "code": "0500",
  "departDate": "15-05-2022",
  "departTime": "16:30",
  "arrivalTime": "19:45"
}

###

GET {{ baseurl }}/api/v1/flights/1
Accept: application/json





