CREATE TABLE FLIGHT(
    ID INT PRIMARY KEY,
    CODE INT NOT NULL,
    NBR_OF_PASSENGERS INT NOT NULL,
    AIRLINE_COMPANY_ID INT REFERENCES AIRLINE_COMPANY(id),
    DEPART_AIRPORT_ID INT REFERENCES AIRPORT(id),
    ARRIVAL_AIRPORT_ID INT REFERENCES AIRPORT(id),
    DEPART_DATE DATE NOT NULL,
    DEPART_TIME TIME NOT NULL,
    ARRIVAL_TIME TIME NOT NULL
)