CREATE TABLE RESERVATION(
    ID INT PRIMARY KEY,
    STATUS VARCHAR(255) NOT NULL,
    RESERVATION_DATE TIMESTAMP NOT NULL,
    FLIGHT_CLASS_ID INT REFERENCES FLIGHT_CLASS(id),
    CLIENT_ID INT REFERENCES PERSON(id),
    PASSENGER_ID INT REFERENCES PERSON(id),
    FLIGHT_ID INT REFERENCES FLIGHT(id)

)